### PR TITLE
drop support for deprecated rails versions

### PR DESCRIPTION
**Pull request by grosser**

### CODE REVIEW

**Comment by fatkodima** [comment]
This also can be removed https://github.com/collectiveidea/audited/blob/9f6619ca48d3f8e0809ca7d02451a95b7f530be3/lib/audited/auditor.rb#L165

**Comment by grosser** [comment]
done, good to go ?

**Comment by fatkodima** [comment]
Looks like readme should be changed here
> Audited currently (4.x) works with Rails 5.1, 5.0 and 4.2. It may work with 4.1 and 4.0, but this is not guaranteed.

And added missing changelog entry

**Comment by grosser** [comment]
helper is still needed since I'm not removing rails 4.2

**Comment by grosser** [comment]
updated and green

**Comment by grosser** [comment]
review plz

**Comment by fatkodima** [comment]
@tbrisker Did you proposed to delete all 4.x (so 4.2 as well) rails versions, or just 4.0 and 4.1?

**Comment by tbrisker** [comment]
I suggested dropping all in #430, but perhaps it would be better to split it in two and keep just 4.2 in the stable 4.x branch, considering that 4.{0,1} have not been officially supported for some time.

**Comment by grosser** [comment]
don't think there is disagreement over dropping 4.0/4.1 ... just maybe 4.2
... also I'll need this as base for other PRs to not merge-conflict myself
:D

**Comment by tbrisker** [comment]
Considering we haven't been supporting them officially for at least 2 years, I guess it's safe to drop. Thanks @grosser !

**Pull request merged**
