### PR TITLE
display class and id for deleted users

### PR DESCRIPTION
**Pull request by grosser**
was about to make a PR when I realized it's not that easy ... since user should behave like a AR and most likely not return a weird string ... maybe user_as_string should do that instead and user should be aliased to something else ... idk ... 
/fyi @danielmorrison

### CODE REVIEW

**Comment by danielmorrison** [comment]
I'm ok rethinking that behavior (as long as we don't have breakages). What's the goal you're going for here?

**Comment by grosser** [comment]
I wanted to show something in the UI when a user got deleted ... atm I'm
solving it in the view, but I though something like user_as_string should
try as hard as possible to display something ... on the other hand it could
be a security issue to leak user ids ... so more of a 'what do you think'
PR ... solved for me now so I can go either way

**Comment by tbrisker** [comment]
Is this still wip @grosser?

**Comment by grosser** [comment]
updated and ready to merge 🎉

**Comment by grosser** [comment]
hmmm tests failed, might need more rework ... I guess I'll just close this until it bothers me again ...

**Pull request closed without merging**
