### PR TITLE
Replace RequestStore with ActiveSupport::CurrentAttributes

### PR DESCRIPTION
**Pull request by punkisdead**
Based on the work done here: https://github.com/collectiveidea/audited/pull/673 by @the-spectator

### CODE REVIEW

**Comment by punkisdead** [comment]
Since `ActiveSupport::CurrentAttributes` was introduced in Rails 5.2 [Rails 5.2 Release](https://guides.rubyonrails.org/5_2_release_notes.html#active-support-notable-changes) I had to increase the minimum required version of `activesupport` and `activerecord` to 5.2.

I'm not entirely sure why the Fiber spec would pass on Rails 7.0 and not previous versions, but I'm not entirely sure we need that spec in this gem? ¯\_(ツ)_/¯ 

Even in current Rails, the default isolation level is set to `:thread` according to [Configuring Rails](https://guides.rubyonrails.org/v7.0/configuring.html#config-active-support-isolation-level)

**Comment by punkisdead** [comment]
I can take a look at it...

**Comment by danielmorrison** [comment]
I can't remember offhand why we added the fiber spec. Probably sanity check for… something. 🤷

**Review by danielmorrison — APPROVED** [review]

**Comment by punkisdead** [comment]
giphy

**Pull request merged**
