### PR TITLE
Allow users to set types for all id columns

### PR DESCRIPTION
**Pull request by vassilevsky**
Hello :)

Thank you for the wonderful gem!

We use UUID for all id columns and this is something that we would need.

Let me know if anything else is needed.

### CODE REVIEW

**Comment by fatkodima** [comment]
I don't think this is that hard to do it manually after migration was generated to complicate things.
So I'm 👎 on this.

**Comment by vassilevsky** [comment]
Yep, it's really easy to edit the generated migration. Do you think all options can be removed then?

**Comment by fatkodima** [comment]
Yes, I think so. I have proposed that here https://github.com/collectiveidea/audited/issues/430#issuecomment-377825088
but has not yet received any feedback.

**Comment by josephpage** [comment]
I think it should be completely removed, but it should use the default column type from Rails.
The one which can be configured with 
```
config.generators do |g|
  g.orm :active_record, primary_key_type: :uuid
end
```
I can work on it in my PR #433

**Comment by vassilevsky** [comment]
I have created #434 that completely removes options instead :)

**Pull request closed without merging**
