### PR TITLE
Use RequestStore instead of Thread.current for thread-safe requests.

### PR DESCRIPTION
**Pull request by tiagocassio**
Related to: https://github.com/collectiveidea/audited/issues/601 and inspired by: https://github.com/paper-trail-gem/paper_trail/commit/e28d29ef0f58cded1537df57551b73ac5b081b36

### CODE REVIEW

**Comment by danielmorrison** [comment]
This is good. Thanks!

**Review by danielmorrison — APPROVED** [review]

**Review by danielmorrison — CHANGES_REQUESTED** [review]
Looks like the tests need some work.

**Review by danielmorrison — APPROVED** [review]

**Comment by mroach** [comment]
What's the motivation with using another gem as opposed to [ActiveSupport::CurrentAttributes](https://api.rubyonrails.org/classes/ActiveSupport/CurrentAttributes.html)?  My understanding of `CurrentAttributes` is that it's designed specifically to deal with this problem, and it's already available due to the indirect dependency via `ActiveRecord`.

**Comment by danielmorrison** [comment]
I like the idea of moving to ActiveSupport::CurrentAttributes. I'd love to see a PR with that.

**Pull request merged**
