### PR TITLE
feat(gemspec): add activerecord 6.1

### PR DESCRIPTION
**Pull request by bonekost**
fixed support for Rails 6 #488

### CODE REVIEW

**Comment by phildionne** [comment]
Now that rails 6.0.0.rc1 is out, could you please merge this :)

Thanks!

**Comment by phildionne** [comment]
@domcleal any chance you can merge this soon? It it would be great :) Thanks!

**Comment by pominx** [comment]
WeI also need this for Rails 6, thanks!

**Comment by tbrisker** [comment]
@bonekost thanks for the PR! Can you please also testing to the .travis.yml file so we know the tests actually pass and there are no regressions when using audited with Rails 6?

**Comment by trevorrjohn** [comment]
I was impatient and added updated the travis.yml and gemfile here https://github.com/collectiveidea/audited/commit/03e3b5aa9d104e910a6d5929179757a2cc6772e7 @bonekost, feel free to cherry-pick it

**Comment by morgoth** [comment]
Would it actually be possible to unlock upper version requirement, to not have this problem on future updates?

**Comment by trevorrjohn** [comment]
> Would it actually be possible to unlock upper version requirement, to not have this problem on future updates?

I don't think this is a good idea. Each version should be tested and would be a terrible experience if someone was trying to use the gem with a new version that wasn't supported.

**Comment by trevorrjohn** [comment]
Opened a new PR https://github.com/collectiveidea/audited/pull/493 for this.

**Comment by domcleal** [comment]
Thanks for that @trevorrjohn. I see the 6.0 tests aren't passing at the moment unfortunately.

I did start a branch updating them recently too, but hadn't quite got it the older combinations working. I'll see if I can finish that off and open up a candidate PR too. (https://github.com/domcleal/audited/commits/rails60-test)

**Comment by domcleal** [comment]
I've opened #494 with a few more fixes - sorry to confuse matters with more PRs!

**Comment by domcleal** [comment]
Thanks for your PRs @bonekost and @trevorrjohn, 494's now merged into master and is awaiting release.

**Pull request closed without merging**
