### PR TITLE
Replace RequestStore with `ActiveSupport::CurrentAttributes`

### PR DESCRIPTION
**Pull request by the-spectator**
Followup of https://github.com/collectiveidea/audited/pull/669

This PR is an attempt to use `ActiveSupport::CurrentAttributes` instead of the `RequestStore` gem.

### CODE REVIEW

**Comment by flipsasser** [comment]
👏 thank you @the-spectator!

**Comment by akshay-birajdar** [comment]
A friendly bump for the reviewers!

**Review by danielmorrison — APPROVED** [review]

**Comment by danielmorrison** [comment]
I have merge regrets. I stupidly didn't wait for all the tests to pass.

**Comment by danielmorrison** [comment]
I reverted this. I'd love to merge a version of it again, but not with all the test failures we were seeing. 

Unfortunately, chasing down those test failures isn't high on my priority list.

**Pull request merged**
