### PR TITLE
add nested auditing

### PR DESCRIPTION
**Pull request by KevinColemanInc**
related issue:
https://github.com/collectiveidea/audited/issues/449

### CODE REVIEW

**Comment by tbrisker** [comment]
@KevinColemanInc Thanks! can you please also add a line about this to the CHANGELOG?

**Comment by KevinColemanInc** [comment]
done

**Comment by grosser** [comment]
@tbrisker lots of PRs ready to merge ... if you don't have time to review, maybe add another maintainer ?

**Comment by tbrisker** [comment]
@grosser - I had a lot of travel over the last month that greatly impacted my ability to dedicate time to this gem. Sadly, I don't have permissions to add other maintainers, only @danielmorrison does afaik. However, I don't see anyone other than me doing reviews atm, so I'm not sure who would be a good candidate as an additional maintainer even if I could give the permission.

**Pull request merged**
