### PR TITLE
Use updated AR::Dirty API to find changed attributes

### PR DESCRIPTION
**Pull request by ulfmagnetics**
Fixes https://github.com/collectiveidea/audited/issues/371

### CODE REVIEW

**Comment by darryn02** [comment]
+1
@danielmorrison Thoughts on this? These deprecation warnings are a killer for CI output.

**Comment by darryn02** [comment]
🎊 
Thank you @danielmorrison !!

**Comment by antond** [comment]
Great to see that this is fixed - thanks 👍. Any estimate on when this will be released?

**Comment by tbrisker** [comment]
@antond this is now released in version 4.6.0

**Pull request merged**
