### PR TITLE
Audit Batches using activerecord-import

### PR DESCRIPTION
**Pull request by mattboldt**
### Checklist
- [ ] Specs for `Audited::AuditBatch`

### CODE REVIEW

**Comment by phildionne** [comment]
@mattboldt what's the status on this? It would be really useful to see this go through :)

**Comment by mattboldt** [comment]
@phildionne Unfortunately, I haven't had the time to work on this 😢 But I too am still very interested in seeing it implemented. Maybe over the upcoming holidays?

**Comment by jesseduffield** [comment]
I just came across this use case myself. @mattboldt do you intend to revisit this PR?

**Comment by mattboldt** [comment]
@jesseduffield It's been a while since I've used this gem, so I'm not sure if/when I'll get back to this PR. It does seem useful and like there's interest, though. I'll close it for now, but open it again if I pick it back up. Feel free to fork or open your own PR in the meantime!

**Pull request closed without merging**
