### PR TITLE
Add tests for Rails 5.2

### PR DESCRIPTION
**Pull request by mrhead**
Rails 5.2 is imminent so we should add support for it.

### CODE REVIEW

**Comment by tbrisker** [comment]
@mrhead looks like now tests for 5.1 fail on mysql, care to check why?

**Comment by tbrisker** [comment]
disregard my comment, looks like #387 fixes this issue - apparently 5.2.0.beta2 < 5.2 causing the failures in CI.

**Comment by mrhead** [comment]
@tbrisker Awesome :)

**Comment by mrhead** [comment]
Anyway, just let me know if there is any action needed. I'll be happy to check it.

**Pull request merged**
