### PR TITLE
Support multiple databases

### PR DESCRIPTION
**Pull request by michael-groble**
We would like to store the `audits` table in a separate database.  With Rails 6 or [ankane/multiverse](https://github.com/ankane/multiverse), I can do that by setting up an abstract base record for all models I want to store in a secondary database:

```ruby
class SecondaryRecord < ActiveRecord::Base
  self.abstract_class = true
  connects_to database: { writing: :secondary, reading: :secondary_replica }
end
```
and would then want to set up the audit model to live there:
```ruby
class CustomAudit < SecondaryRecord
end
```

But since that `CustomAudit` record does not inherit from `Audited::Audit`, this won't really work.

This pull request creates an `Audited::Auditable` concern which lets me store audits in the secondary database like so:

```ruby
class CustomAudit < SecondaryRecord
  include Audited::Auditable
end
```

### CODE REVIEW

**Comment by brand-it** [comment]
```
NotImplementedError:
  Audit is an abstract class and cannot be instantiated.
  # /Users/blareau/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/activerecord-6.0.2/lib/active_record/inheritance.rb:52:in `new'
```
@michael-groble Did you get the error above and if so how did you work around the issue?

**Comment by michael-groble** [comment]
I see failures in travis, @brand-it, but things run cleanly for me locally (on macos), e.g.:
```bash
bundle exec rake
bundle exec appraisal rails50 rake
bundle exec appraisal rails51 rake
bundle exec appraisal rails52 rake
bundle exec appraisal rails60 rake
```
(and the travis errors don't seem to match that abstract class error)

**Comment by LukeGuanY** [comment]
Hi @michael-groble, I also have the same need that writing the audit logs to the second database. But I am having trouble with how to tell the CustomAudit to write the audit logs to the second database. Could you please tell me how to point audited to the second DB in the CustomAudit file?

**Comment by michael-groble** [comment]
@LukeGuanY , that really depends on how you connect to multiple databases in the first place.  I give an example above of rails 6.  You can also set up a base that connects to a specific entry in you database configuration.  For example, say your database config has a separate set of configuration for "warehouse" type tables, e.g.

```
production:
  ...
  database: app_production
  warehouse:
    ...
    database: warehouse_production
```
then you can have a base record (rails 5 this time)
```
class WarehouseRecord < ApplicationRecord
  self.abstract_class = true
  establish_connection configurations[Rails.env]['warehouse'] if configurations[Rails.env]['warehouse']
end

class CustomAudit < WarehouseRecord
  include Audited::Auditable
end
```

**Comment by LukeGuanY** [comment]
@michael-groble Thanks for the reply. I really appreciate your method. I am sharing my configuration here so that people can also learn it. 

I use the multiple database feature on Rail 6

Database.yml:
```
development:
  primary:
    database: the_existing_db
    ...
  audit:
    database: audit_db
    migrations_paths: db/audit_migrate #you need to create a new folder called "audit_migrate" under db directory
```

Make an audit initializer at  `config/initializers/audited.rb` 
```
# Make Audited send its data to a different database
Audited::Audit.class_eval do
  establish_connection :audit
end
```

**Comment by vinayuttam** [comment]
The above suggestion works fine up to version `v5.0.1`.  With the recent update `v5.0.2`, we get the following error
```
config/initializers/audited.rb:3:in `<main>': uninitialized constant Audited::Audit (NameError)
Did you mean?  Audited::Auditor
```

**Comment by amkisko** [comment]
Probably related to this one https://github.com/collectiveidea/audited/pull/641

**Pull request closed without merging**
