### PR TITLE
Support for Rails 6.1

### PR DESCRIPTION
**Pull request by yknx4**
Required changes to support Rails 6.1

- Remove deprecated method calls
- Update Gemspec
- Update Travis Config

### CODE REVIEW

**Comment by jsantos** [comment]
@yknx4 Thanks for your contribution! If possible include a description on the PR, and we might also need to add Appraisals support including a `gemfiles/rails61.gemfile`, which should look like this:

```ruby
# This file was generated by Appraisal

source "https://rubygems.org"

gem "rails", ">= 6.1.0", "< 6.2"
gem "mysql2", ">= 0.4.4", "< 0.6.0"
gem "pg", ">= 0.18", "< 2.0"
gem "sqlite3", "~> 1.4"

gemspec name: "audited", path: "../"
```

**Comment by yknx4** [comment]
@jsantos on it ~ :+1:

**Comment by jsantos** [comment]
Can any of the maintainers get this merged? I see some builds failing on the CI but these doesn't seem to be consistent... Tried to replicate locally with the same Ruby versions and all was clean. \cc @danielmorrison

**Comment by jmeattle** [comment]
Much appreciate all your hard work. It would be really great if this PR can be merged soon.

**Comment by emileriksson** [comment]
Any updates on when this is getting merged??

**Comment by altmer** [comment]
Is there anything we can do to help to get this merged?

**Comment by barrywoolgar** [comment]
> Is there anything we can do to help to get this merged?

At a guess, managing to get all the CI tests to pass might help. Could be a Travis configuration issue as opposed to a problem with the PR changes, but not sure how that gets debugged without being a maintainer.

**Comment by danielmorrison** [comment]
Thanks for the work @yknx4! Apologies that I've had zero time to look at this. 

Thanks to @jmortlok for fixing the build. I merged a few easy things, and i'll cut a release soon.

**Pull request merged**
