### PR TITLE
Rails 4.2 support

### PR DESCRIPTION
**Pull request by miks**
Can we make dedicated 4.2 release for rails 4.2?

### CODE REVIEW

**Comment by miks** [comment]
Fixed.

**Comment by robmathews** [comment]
Tripping over this issue in rails 4.2 - w/o this fix, it doesn't work. Any plans to merge?

**Comment by mordocai** [comment]
I'm currently working on moving to rails 4.2 and this is going to bite me. Would really appreciate it being merged ASAP.

**Comment by robmathews** [comment]
My reaction to this was to switch to paper_trail.

It seems much more active and full featured. It has a "revert" function,
for example.

**Comment by mordocai** [comment]
I feel a bit like a jerk discussing this in the issue on audited, but oh well. 

Unfortunately, I already have a considerable amount of production logs with audited so it'd be a real pain to migrate to something else.

I don't want to support audited myself though so if that's the other option I may take a look paper_trail.

I suppose I could always fork but I don't really want to maintain a persistent fork.

**Comment by teknull** [comment]
I can see this being a big issue as we all migrate to 4.2.  I've had a lot of problems with the gem in Rails 3.2.x now that I'm upgrading multiple apps to 4.2 this concerns me.  Can we have compatibility and a gem release, please?

**Pull request merged**
