### PR TITLE
Bump version and refresh changelog for 4.5.0

### PR DESCRIPTION
**Pull request by domcleal**

### CODE REVIEW

**Comment by westonplatter** [comment]
@domcleal would it be worth changing to README to say that the gem is supported for Rails 5.0.x and 5.1.x?

**Comment by domcleal** [comment]
@westonplatter it already says: "Audited currently (4.x) works with Rails 5.1, 5.0 and 4.2."

**Comment by ericsaboia** [comment]
could we please have this merged? :D

**Comment by ericsaboia** [comment]
@domcleal and @danielmorrison can we please merge this? this probably affecting a lot of people right now.

**Comment by danielmorrison** [comment]
Done.

**Comment by domcleal** [comment]
Thanks @danielmorrison.

**Pull request merged**
